// Code generated by "stringer -type Attr"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttrDate-0]
	_ = x[AttrLikes-1]
	_ = x[AttrViews-2]
	_ = x[AttrRandom-3]
}

const _Attr_name = "AttrDateAttrLikesAttrViewsAttrRandom"

var _Attr_index = [...]uint8{0, 8, 17, 26, 36}

func (i Attr) String() string {
	if i < 0 || i >= Attr(len(_Attr_index)-1) {
		return "Attr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Attr_name[_Attr_index[i]:_Attr_index[i+1]]
}
